### ISSUE TITLE
Name of the project

### ISSUE THREAD

**Issue by klokan** [stirringhalo/openstreetmap-mapboxgl#4]
Great effort here!

I suggest renaming the project to "openstreetmap-gl" or another name not having word "mapbox" in it.

MapBox is a name of a company - and a registered trademark. You may get into trouble at some point - and they are not affiliated anyhow to this project I guess.

**Comment by stirringhalo** [comment]
I'm not against the name change or a mention of the trademark of Mapbox. I looked into it and CartoCSS and MBTiles are also registered trademarks of Mapbox. I don't see any mention of that in openstreetmap-carto!

@michaelsteffen , I did a brief look and couldn't find whether MapboxGL (or similar) is a registered trademark but I know "Mapbox" indeed is. I have "openstreetmap-mapboxgl" as the name to reflect the library in use, akin to the "openstreetmap-carto" project which uses the "CartoCSS" trademark. Is this use of "MapboxGL" violation of any trademark? If so, please advise what is the most appropriate action, such as a mention of the trademark or a name-change.

**Comment by stirringhalo** [comment]
I will close this for now until I hear anything different from @michaelsteffen .

**Comment by michaelsteffen** [comment]
@stirringhalo can you reach out directly?  I'd love to hear a little more about what this is before I reply . . . Tried to track down your contact info here but without success. I'm michael at mapbox.

**Comment by stirringhalo** [comment]
@michaelsteffen . I sent you an email at that address a number of days ago but hadn't seen a response.

**Comment by michaelsteffen** [comment]
@stirringhalo - Following up on our email exchange - We're fine with MapboxGL being used here to parallel openstreetmap-carto and reflect the library in use, as long as it's clear that it's not affiliated with Mapbox. As long as you do that, we're good with this repo name. Thanks for checking!

**Comment by stirringhalo** [comment]
Great, thanks. See aff47b4 for the change and congrats!
